### ISSUE TITLE
How to edit tables without primary key? (e.g. xref )

### ISSUE THREAD

**Issue by spazm** [bigpresh/Dancer-Plugin-SimpleCRUD#25]
Thanks for your module.  I'm using it during a hackathon at work, so I can quickly import and edit some data in my project.  

Use case: three small tables: projects, users, and project_user_xref.    project_user_xref has two fields, project_id and user_id, which are foreign keys pointing to projects.id and users.id.  I am currently stumped on how to modify this table via D-P-SimpleCRUD.

Similarly, I had a problem with my original users table, which had a primary key of "users.name".  Since that didn't work well, I added a synthetic id field (autoinc integer primary key), and I was able to use SimpleCRUD for my users and my projects.

Thanks for any tips.

**Comment by bigpresh** [comment]
... this has sat for some time!

I'm going to close this, as I think "tables must have a unique identifier column" is a reasonable choice, and I don't forsee having the time available (or, indeed, a burning desire) to do the work to support tables that don't have an ID column.  Sorry!

**Comment by spazm** [comment]
closing was a good idea.

FWIW: I'd totally forgotten about this :)
And also forgotten what hackathon project I was working on in 2013.

**Comment by arpanpreneur** [comment]
@bigpresh I don't agree with your statement " \"tables must have a unique identifier column\" is a reasonable choice".
Reason: I am using PostgreSQL Citus in which I want to shard my multi-tenant tables with tenant_id. Now in order for citus to work, the shard key tenant_id needs to be a part of the primary key set mandatorily. If we do a Get operation or any other operation without the tenant_id, it will run the query in all the shards.

I would argue, this is a very reasonable choice for Citus DB to force the distrubution column to be a part of primary key. So that it can tell from the where condition itself which shard to run this query on.

For this reason, it is super hard for me to get any benefit of this library.

**Comment by bigpresh** [comment]
Fair point.  I think then umber of people using sharding like that, but still wanting to use a "::Simple*" CRUD library like these is probably fairly small, though.  My thoughts on handling multiple column primary keys earlier in the ticket (for e.g. how to represent that reliably in the URLs - at the moment, you know easily that `/$prefix/42` will get you an editing form for the row whose identifier column has the value 42 - that all gets more complex if there can be multiple columns making up the identifier) still stand, I think.

If you have some cunning ideas on how it should work I'm more than happy to hear them, but I don't want to move away from the "simple, works for the majority of people likely to use this" to support relatively unusual cases like yours if it causes extra complexity for the typical user.

My initial thought is the same as before, that the `key_column` could be an arrayref of columns, e.g. `key_column => [ 'tenant_id', 'thing_id' ]`, and generate URLs to represent objects as e.g. `/prefix/12/34`, `/prefix/12/34/edit` - where the values for each column within `key_column` are in the URL path... but would need to be careful for cases like "what if one of the values should contain an actual `/`... I suppose as long as the values get URL-encoded carefully that should be OK?
